apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  selector:
    matchLabels:
      run: backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: docker.io/solayunus/udagram-api-feed:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 500m
            memory: "1024Mi"
          limits:
            cpu: 1000m
            memory: "8192Mi"
        env:
            - name: POSTGRES_USERNAME
              value: 'yunusdb'
            - name: POSTGRES_PASSWORD
              value: myproject3
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_HOST
              value: database-1.c1p0qczgcbjl.us-east-1.rds.amazonaws.com
   
            