apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  selector:
    matchLabels:
      run: backend-user
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-user
    spec:
      containers:
      - name: backend-user
        image: docker.io/solayunus/udagram-api-user:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1000m
            memory: "2092Mi"
          requests:
            cpu: 500m
            memory: "1024Mi"
        env:
          - name: POSTGRES_USERNAME
            value: 'yunusdb'
          - name: POSTGRES_PASSWORD
            value: myproject3
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_HOST
            value: database-1.c1p0qczgcbjl.us-east-1.rds.amazonaws.com