apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  selector:
    matchLabels:
      run: backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: docker.io/solayunus/udagram-api-feed:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
            memory: "128Mi"
          limits:
            cpu: 500m
            memory: "8024Mi"
        envFrom:
        - secretRef: 
            name: env-secret
        - configMapRef: 
            name: env-config
        - secretRef:
            name: mysecret
   
            