apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  selector:
    matchLabels:
      run: reverseproxy
  replicas: 2
  template:
    metadata:
      labels:
        run: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: docker.io/solayunus/udagram-reverseproxy:v1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 500m
        